name: Run evals

on:
  push:
    paths:
      - 'src/main/ai/**'

jobs:
  eval:
    runs-on: macos-latest
    timeout-minutes: 10
    env:
      EVALS_OPENAI_API_KEY: ${{ secrets.EVALS_OPENAI_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run evals
        run: bun run evals
