name: Lint, type-check and build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run TypeScript check for main
        run: bun run build:main

      - name: Run TypeScript check for renderer
        run: bun run build:renderer

      - name: Build Electron app
        run: bun run build
